### ISSUE TITLE
Aim in Left Mouse Button

### ISSUE THREAD

**Issue by isvktt** [RootKit-Org/AI-Aimbot#10]
how do i make the aim work only when pressing the left mouse button ? I managed to put it on the left button but it is deactivating and activating, I would like it to work only when I press

**Comment by Qfc9** [comment]
We may make it easier in a future update to edit. For now you need to edit this line
https://github.com/RootKit-Org/AI-Aimbot/blob/9787b43034085faab5a3302fd98466dc2b9f64fa/main.py#L129

**Comment by isvktt** [comment]
yea, but I opened a ''ticket'' here to make it work by pressing the key and not just clicking, you know?

**Comment by isvktt** [comment]
do you know how i can do this?
