### ISSUE TITLE
Import "utils.general" could not be resolved

### ISSUE THREAD

**Issue by SapphirePredictor** [RootKit-Org/AI-Aimbot#101]
I have installed all of the requirements from the file and it gives me this error anyways.

**Comment by Parideboy** [comment]
What version of Python are you using? What version are you trying to run?

**Comment by SapphirePredictor** [comment]
I am on 3.10.9 and trying to use the main.py file

**Comment by Parideboy** [comment]
Try to uninstall all the requirements and install them from scratch:

pip uninstall -r requirements.txt -y
pip install -r requirements.txt -y
