### ISSUE TITLE
AI detects but doesnt move the mouse to the target

### ISSUE THREAD

**Issue by Ardispicy** [RootKit-Org/AI-Aimbot#102]
I can see the AI is detecting people from the live feed, but the AI is not moving the mouse. What is the issue? There is no error message on the terminal. Can someone help? The libraries required are installed.

**Comment by Ardispicy** [comment]
yes it works in halo but not in csgo

**Comment by NEEDSPOOFER** [comment]
can u teach how to compile it

**Comment by BenigJester** [comment]
Just run cmd as administrator
`cd <aimbot-source>`
Then do the magic.
