### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by isvktt** [RootKit-Org/AI-Aimbot#11]
is it possible to make triggerbot ?

**Comment by bombitmanbomb** [comment]
Adding auto-fire is not at all out of the realm of possibility
The following code will send a Left-Click event

```py
def leftClick():
    win32api.mouse_event(win32con.MOUSEEVENTF_LEFTDOWN,0,0)
    time.sleep(.1)
    win32api.mouse_event(win32con.MOUSEEVENTF_LEFTUP,0,0)
```
I wouldn't recommend using this exact code as the sleep statement will temporarily halt execution, but am providing it as an example of how one could add such functionality

**Comment by KoenigseggTurbo** [comment]
the script cant find game window
