### ISSUE TITLE
The game window you are trying to select doesn't exist. Check variable videoGameWindowTitle (typically on line 13

### ISSUE THREAD

**Issue by KoenigseggTurbo** [RootKit-Org/AI-Aimbot#12]
I am receiving this issue whenever i try to start any game

**Comment by bombitmanbomb** [comment]
Did you [Configure the Bot](https://github.com/RootKit-Org/AI-Aimbot#configurable-settings)?
By default the bot looks for the game Counter Strike.
[See Line 13](https://github.com/RootKit-Org/AI-Aimbot/blob/59f70fb03b7f802c75f1e7d87262f6bf0f6a3a75/main.py#L13)

**Comment by KoenigseggTurbo** [comment]
How do I configure it for other games

Sent from Yahoo Mail on Android 
 
  On Thu, May 5, 2022 at 7:01 AM, Ethan ***@***.***> wrote:   


Did you Configure the Bot?
By default the bot looks for the game Counter Strike.
See Line 13

**Comment by bombitmanbomb** [comment]
Set the text on that line to something in the video game window title.

**Comment by Qfc9** [comment]
Join the discord for more support. This is not an issue with the application
