### ISSUE TITLE
whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by XXXXXY1** [RootKit-Org/AI-Aimbot#125]

**Comment by XXXXXY1** [comment]
![Uploading 5926d752632805aafdd8942d871c171.png…]()

**Comment by XXXXXY1** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by Qfc9** [comment]
Ask Wonder bot in the discord

**Comment by XXXXXY1** [comment]
thank you！谢谢
