### ISSUE TITLE
ModuleNotFoundError: No module named 'bettercam'

### ISSUE THREAD

**Issue by glpc** [RootKit-Org/AI-Aimbot#126]
Traceback (most recent call last):
  File "C:\Users\glp\Desktop\fps-RootKit-Org-AI-Aimbot\AI-Aimbot-3.0.0\main_onnx.py", line 18, in <module>
    import gameSelection
  File "C:\Users\glp\Desktop\fps-RootKit-Org-AI-Aimbot\AI-Aimbot-3.0.0\gameSelection.py", line 3, in <module>
    import bettercam
ModuleNotFoundError: No module named 'bettercam'

**Comment by DingleArfsten** [comment]
i have the same problem did you find a way to fix it?

**Comment by glpc** [comment]
> i have the same problem did you find a way to fix it?

No, I want to build my own version and upload it to pypi.

**Comment by Qfc9** [comment]
pip install git+https://github.com/RootKit-Org/BetterCam

**Comment by Qfc9** [comment]
We are working on gettting it on pypi right now

**Comment by Qfc9** [comment]
Fixed

**Comment by SYIRUL94** [comment]
AttributeError: 'BetterCam' object has no attribute 'is_capturing' and this happen. help

**Comment by MattPlayGamez** [comment]
> AttributeError: 'BetterCam' object has no attribute 'is_capturing' and this happen. help

I have the same issue

**Comment by MattPlayGamez** [comment]
Not supported?
