### ISSUE TITLE
unsupported operand type(s)

### ISSUE THREAD

**Issue by f3ds-lol** [RootKit-Org/AI-Aimbot#131]
File "G:\AI-Aimbot-main\gameSelection.py", line 10, in <module>
    def gameSelection() -> (bettercam.BetterCam, int, int | None):
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**Comment by StandartCoder** [comment]
remove | None from def gameSelection() -> (bettercam.BetterCam, int, int | None):

**Comment by yurithome123** [comment]
or remove | None from def gameSelection() -> (bettercam.BetterCam, int, int | Null):

**Comment by SnowHubv2** [comment]
> File "G:\AI-Aimbot-main\gameSelection.py", line 10, in def gameSelection() -> (bettercam.BetterCam, int, int | None): TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

**FIX**

upgrade python to 3.11

or just "remove | None from def gameSelection() -> (bettercam.BetterCam, int, int | None):" as the others said
