### ISSUE TITLE
[SOLUTION] The specified device interface or feature level is not supported on this system

### ISSUE THREAD

**Issue by ManuGalzerk** [RootKit-Org/AI-Aimbot#133]
'The specified device interface or feature level is not supported on this system'
AttributeError: 'BetterCam' Object has no attribute 'is_capturing'

I hope it's works! 
Anyway
This is the guide to fix that issue.

![IMG_3713](https://github.com/RootKit-Org/AI-Aimbot/assets/50106708/02268868-089b-4bdb-8d1d-5ac94d2b7e79)

NVIDIA
NVIDIA Control Panel > Manage 3D Settings > Preferred graphics processor setting.

For AMD i don't know where to go!

**Comment by LouisDrae** [comment]
That worked, thank you!

**Comment by ueeseer** [comment]
Tried but not working. I am using a conda environment python. I added the path of the anaconda python. I wonder if that make different from the standard one.
