### ISSUE TITLE
Aimbot Not working

### ISSUE THREAD

**Issue by Gearingg** [RootKit-Org/AI-Aimbot#145]
I'm having a trouble with the Aimbot as its not aiming in the game at all. But everything else works fine. idk what the problem is but everything else works Such as detecting enemies and auto fire.

I tried updating the drivers, restarting the game and the bot, Running as Admin, Doing a fresh Install of the bot But it still didn't work. bot's toggle is on ( checked multiple times )

**Comment by Qfc9** [comment]
Join the discord and ask Wonder.
