### ISSUE TITLE
cd command not working

### ISSUE THREAD

**Issue by isala009** [RootKit-Org/AI-Aimbot#147]
C:\Users\Test>cd D:\downloads\AI-Aimbot-3.1.0\AI-Aimbot-3.1.0

C:\Users\Test>python main_onnx.py
Python was not found; run without arguments to install from the Microsoft Store, or disable this shortcut from Settings > Manage App Execution Aliases.

**Comment by Qfc9** [comment]
Ask wonder in discord. Looks like you didn't follow any of the follow up
