### ISSUE TITLE
no automatic tracking in the game

### ISSUE THREAD

**Issue by ycgkwyc** [RootKit-Org/AI-Aimbot#15]
no automatic tracking in the game, the mouse cannot move automatically

**Comment by Qfc9** [comment]
This is a non descriptive issue

**Comment by ycgkwyc** [comment]
Unable to determine if the feature is on or off. i change # if win32api.GetKeyState(0x14):    #CAPS LOCK key to GetKeyState(0x02):     #Right mouse button

**Comment by ycgkwyc** [comment]
but i can see bot drawn characters.

**Comment by Qfc9** [comment]
https://github.com/RootKit-Org/AI-Aimbot/blob/59f21f16555083d09aeb38780c66d0ee7af4c7e6/README.md?plain=1#L111
