### ISSUE TITLE
The process automatically ends when the code runs

### ISSUE THREAD

**Issue by oneupevil1** [RootKit-Org/AI-Aimbot#152]
Why does my code automatically end the process when it runs? "The process has ended and the exit code is -1073741819 (0xC0000005)" is displayed.

**Comment by oneupevil1** [comment]
![Uploading 20240106140128.png…]()

**Comment by oneupevil1** [comment]
I can run when I enable other run modes and see the corresponding CPS and detect the target but do not move my mouse. Why?

**Comment by oneupevil1** [comment]
I tried and tried again and found that the mouse didn't move automatically when I was running the game, and could be moved by code when the game wasn't started. Why is that?

**Comment by vouzawyd** [comment]
Application Error code 0xc0000005, also known as Access Violation error, is a common problem experienced by Windows users, regardless of os version. There are various causes to trigger Application Error 0xc0000005

**Comment by YYF6789** [comment]
check the version of torch and torchversion, this should be the same as the cuda
![_9H6NG%VGXCFQLW{DSO3H2B](https://github.com/RootKit-Org/AI-Aimbot/assets/100287637/3e268c42-4faa-40a6-88f3-c77df25f3f90)
