### ISSUE TITLE
is this detectable(fortnite)?

### ISSUE THREAD

**Issue by Mikelll123** [RootKit-Org/AI-Aimbot#156]
if i use it lowk will i get banned, also will fortnite detect it

**Comment by topgkai** [comment]
> if i use it lowk will i get banned, also will fortnite detect it

You cannot get banned for this.

**Comment by JuJuBunz** [comment]
prob, their anti cheats pretty good with ai cheats

**Comment by ExtortedNextrix** [comment]
no eac doesnt detect mouse movement only clicking thats why people make a custom mouse driver or use an arduino
eac cant detect mouse movement because then it would false ban people with good aim and cause a ton of issues

**Comment by OrtaciProYT** [comment]
so if you dont modify the code atleast a bit to fix it up some stuff you are probably getting banned due to epic watching replays of your game and seeing the aimbot but if you dont get reported and just use it on your friends your prob fine
