### ISSUE TITLE
AttributeError: 'BetterCam' object has no attribute 'is_capturing'

### ISSUE THREAD

**Issue by berserkguts458** [RootKit-Org/AI-Aimbot#158]
tried a few things, i still have been getting this error

**Comment by YYF6789** [comment]
You can check “videoGameWindow.activate()” on line 38 of the GameSelection.py.
In my tests in cs2, I found this error appeared when minimizing the window or other windows occluding the target window.

**Comment by 673339641** [comment]
<img width="539" alt="Error" src="https://github.com/RootKit-Org/AI-Aimbot/assets/92238130/8bec40f7-bb1c-48c7-a5e3-c1a4358a9126">
I got 2 error , so I do not know which is the root reason.

**Comment by FCKYuri** [comment]
Please enter the number corresponding to the window you'd like to select: 4
Successfully activated the game window...
(800, 380, 1120, 700)
Traceback (most recent call last):
  File "C:\Users\xxx\Downloads\AI-Aimbot-main\AI-Aimbot-main\main_tensorrt.py", line 166, in <module>
    main()
  File "C:\Users\xxx\Downloads\AI-Aimbot-main\AI-Aimbot-main\main_tensorrt.py", line 20, in main
    camera, cWidth, cHeight = gameSelection.gameSelection()
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\Downloads\AI-Aimbot-main\AI-Aimbot-main\gameSelection.py", line 73, in gameSelection
    camera = bettercam.create(region=region, output_color="BGRA", max_buffer_len=512)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\python3.11\Lib\site-packages\bettercam\__init__.py", line 115, in create
    return __factory.create(
           ^^^^^^^^^^^^^^^^^
  File "E:\python3.11\Lib\site-packages\bettercam\__init__.py", line 72, in create
    camera = BetterCam(
             ^^^^^^^^^^
  File "E:\python3.11\Lib\site-packages\bettercam\bettercam.py", line 34, in __init__
    self._duplicator: Duplicator = Duplicator(
                                   ^^^^^^^^^^^
  File "<string>", line 6, in __init__
  File "E:\python3.11\Lib\site-packages\bettercam\core\duplicator.py", line 19, in __post_init__
    output.output.DuplicateOutput(device.device, ctypes.byref(self.duplicator))
_ctypes.COMError: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
ERROR: (-2005270524, '指定的设备接口或功能级别在此系统上不受支持。', (None, None, None, 0, None))
Ask @Wonder for help in our Discord in the #ai-aimbot channel ONLY: https://discord.gg/rootkitorg
Exception ignored in: <function BetterCam.__del__ at 0x0000020711967CE0>
Traceback (most recent call last):
  File "E:\python3.11\Lib\site-packages\bettercam\bettercam.py", line 248, in __del__
    self.release()
  File "E:\python3.11\Lib\site-packages\bettercam\bettercam.py", line 243, in release
    self.stop()
  File "E:\python3.11\Lib\site-packages\bettercam\bettercam.py", line 143, in stop
    if self.is_capturing:
       ^^^^^^^^^^^^^^^^^
AttributeError: 'BetterCam' object has no attribute 'is_capturing'

**Comment by spacew0rmx** [comment]
changing from Fullscreen to Fullscreen Windowed fixed it for me

**Comment by ChinaVolvocars** [comment]
图形设置 ->python.exe ->图形首选项 节能

**Comment by CHO-CYQ** [comment]
> P.S. 图形设置 ->查找python.exe -> 图形首选项 -> 省电图形设置 ->python.exe ->图形首选项 节能
> 
> ![屏幕截图 2024-05-31 222533](https://private-user-images.githubusercontent.com/11059094/335615408-0aec5462-977d-4821-8a1e-7b1e6d385f01.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NDIzMjMsIm5iZiI6MTcxOTc0MjAyMywicGF0aCI6Ii8xMTA1OTA5NC8zMzU2MTU0MDgtMGFlYzU0NjItOTc3ZC00ODIxLThhMWUtN2IxZTZkMzg1ZjAxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDEwMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2YWIyODI0ZjU3NTg2ZmViZDdiN2EwZGIzOGJlYWZhYzI0YTYzZDZiMjc0YmFhMGZmYThhYWVhNzY4ZTEzZjgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.O0-ZNXyABiSRKh5oyrG39z1CkoGjnMvyjlK-3_ojYZM) ![屏幕截图 2024-05-31 222612](https://private-user-images.githubusercontent.com/11059094/335615433-0403782f-1119-411a-b006-5307592f813a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk3NDIzMjMsIm5iZiI6MTcxOTc0MjAyMywicGF0aCI6Ii8xMTA1OTA5NC8zMzU2MTU0MzMtMDQwMzc4MmYtMTExOS00MTFhLWIwMDYtNTMwNzU5MmY4MTNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjMwVDEwMDcwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA5MzBmNGFhYzk5YjM4ZDg3OTc2OGMxYTE3YjhhNDFlNGIzZDhmYjZmODVhYmI2NzFjYTcyNjY5OTNjZmQwYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.1pPwCNGS01KMIhfIcg6Guy9XK6xQE_lEubhU27-aBMc)

It worked!
