### ISSUE TITLE
run problem

### ISSUE THREAD

**Issue by themichalwilk** [RootKit-Org/AI-Aimbot#164]
as in topic below paste from powershell
all binaries and dependencies were apparently build and install yay ok - yet it's a hard no when it's time to run

PS E:\temp\ai> python.exe .\main.py
E:\temp\ai\main.py:7: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd
Traceback (most recent call last):
  File "E:\temp\ai\main.py", line 9, in <module>
    from utils.general import (cv2, non_max_suppression, xyxy2xywh)
  File "E:\temp\ai\utils\general.py", line 34, in <module>
    import pkg_resources as pkg
ModuleNotFoundError: No module named 'pkg_resources'
PS E:\temp\ai>

**Comment by themichalwilk** [comment]
all resolved

**Comment by spacew0rmx** [comment]
> all resolved

thanks for the solution ◔̯◔
`pip install setuptools`
