### ISSUE TITLE
The luncher is stuck in the login screen 

### ISSUE THREAD

**Issue by jzfed** [RootKit-Org/AI-Aimbot#168]
The luncher is stuck in the login screen even though I have successfully logged in discard
![2024-03-09 03_49_13-RootKit Launcher](https://github.com/RootKit-Org/AI-Aimbot/assets/48242137/b1ded78b-73fc-4b4f-ab69-d729c08e5142)

**Comment by garacio777** [comment]
there's only one option on pop up screen when installing soft
![Screenshot 2024-03-28 135621](https://github.com/RootKit-Org/AI-Aimbot/assets/120954695/190a80f6-d7e7-42d7-a285-85c4e76c4117)

**Comment by garacio777** [comment]
same issue for me

**Comment by 806865832ggg** [comment]
The same problem. I changed my browser, but I still can't log in
