### ISSUE TITLE
AIMBOT FORTNITE ARDUINO

### ISSUE THREAD

**Issue by isvktt** [RootKit-Org/AI-Aimbot#169]
Hi guys, I see that many people are wanting to use it in Fortnite and are having problems, I found this video on a forum where the coder uses aim on Arduino for Fortnite, maybe it can help you!
https://www.youtube.com/watch?v=v7I8__L_4No

**Comment by Kiolermanethan** [comment]
Can I have aimbot please my name is killermanethan
