### ISSUE TITLE
PS C:\Users\User> pip install -r requirements.txt ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

### ISSUE THREAD

**Issue by dean9494** [RootKit-Org/AI-Aimbot#170]

**Comment by OrtaciProYT** [comment]
you have to run CMD or Powershell in the right directory and then do "pip install -r requirements.txt"
you dont have to use Powershell like in most tutorials you can just do the same in CMD like it does in this tutorial
--https://www.youtube.com/shorts/6SoxLhQDiXA--
If you dont understand this its not probably the repository that you want to start learning on and if you just want to abuse this project for aimbot you will infact get banned
