### ISSUE TITLE
How can I use this aimbot and train it to be more accurate with Warzone?

### ISSUE THREAD

**Issue by Reyloso** [RootKit-Org/AI-Aimbot#180]
Hello friend, thank you for your work. I managed to get it working on all the versions you released, but I would like to improve it to be more accurate in Warzone. I am a software developer, but AI is not my strong suit

**Comment by Chasadilla** [comment]
You will need a large dataset of training material (screenshots) at your systems native resolution (higher = better but what you play on) and you need to annotate the data using something like makesense.ai - draw bounding boxes and filter through the data to help identify enemies. From there you will need to train the program with your dataset appx 1000 annotated images for a (barely) functional program, or preferrably 10000 for an ideal training set. You can look up how to conduct training like this on YT. Cheers and goodluck.
