### ISSUE TITLE
How to imporve the screen-capturing performance

### ISSUE THREAD

**Issue by AnnSir233** [RootKit-Org/AI-Aimbot#19]
My graphic card was a RTX3080 and all the environment that the aimbot needs was completely installed，but I can only get the CPS under 30，can I get some solutions？
I put the contents of the console below.

(base) C:\Users\AnnSir\AI-Aimbot>python main.py
Downloading: "https://github.com/ultralytics/yolov5/zipball/master" to C:\Users\AnnSir/.cache\torch\hub\master.zip
YOLOv5  2022-7-25 Python-3.9.7 torch-1.12.0 CUDA:0 (NVIDIA GeForce RTX 3080, 10240MiB)
Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
CPS: 1
CPS: 22
CPS: 21
CPS: 23
CPS: 30
CPS: 28

**Comment by Qfc9** [comment]
That's how to goes sometimes. I recommend trying the new update. We improved performance across the board.
