### ISSUE TITLE
not working on Mac!

### ISSUE THREAD

**Issue by Da-Coder-Jr** [RootKit-Org/AI-Aimbot#193]
not working on Mac! M1 CHIP

**Comment by hikidisn** [comment]
This is not built for mac, respectfully please read the readme before writing an issue.

**Comment by Sekiro21** [comment]
Hi, im wondering how this is installed and how i put this on my compter for valorant, and what the chances of it being detected are, also if yk any good pc spoofers so i dont get gardware banned

**Comment by Da-Coder-Jr** [comment]
Thank You!
