### ISSUE TITLE
AI Aimbot for Valorant

### ISSUE THREAD

**Issue by isvktt** [RootKit-Org/AI-Aimbot#24]
I'm seeing some people saying ''why doesn't it work for valorant ?'', the answer is simple, you need arduino + usb host shield for mouse inputs, I managed to find a person who did this for me, take a look at the video below the value was not too expensive and he managed to make this project work for valorant for me!

Video : https://www.youtube.com/watch?v=z-AK8Q9Ehzs

**Comment by Qfc9** [comment]
Unless you are sponsoring us, you don't get to advertise with us. Free Open Source content is the only exception.
