### ISSUE TITLE
 3rd person shooters,

### ISSUE THREAD

**Issue by 1-Negative-1** [RootKit-Org/AI-Aimbot#34]
could we get it implemented that a character in a 3rd person game is discounted from the algorithm? another program I used to use had this line to prevent such a thing. 
"if len(results.xyxy[0]) != 0: #player detected
                least_crosshair_dist = closest_detection = player_in_frame = False
                for *box, conf, cls in results.xyxy[0]: #iterate over each player detected
                    x1y1 = [int(x.item()) for x in box[:2]]
                    x2y2 = [int(x.item()) for x in box[2:]]
                    x1, y1, x2, y2, conf = *x1y1, *x2y2, conf.item()
                    height = y2 - y1
                    relative_head_X, relative_head_Y = int((x1 + x2)/2), int((y1 + y2)/2 - height/2.7) #offset to roughly approximate the head using a ratio of the height
                    own_player = x1 < 15 or (x1 < self.box_constant/5 and y2 > self.box_constant/1.2) #helps ensure that your own player is not regarded as a valid detection"

Just an idea ty

**Comment by Qfc9** [comment]
Sure if you want to help out and write it in. Right now we make the `aaRightShift` as a quick and dirty work around. But a more proper way of doing it would be to create a static mask.

**Comment by rangeeee** [comment]
> Sure if you want to help out and write it in. Right now we make the `aaRightShift` as a quick and dirty work around. But a more proper way of doing it would be to create a static mask.

how i do that for fortnite ?
