### ISSUE TITLE
AI detects but doesnt move the mouse to the target

### ISSUE THREAD

**Issue by michiel1106** [RootKit-Org/AI-Aimbot#38]
It detects the "humans" (for example in valorant for 50%) but it doesnt move the mouse to the target.
I has only worked on my computer screen, not in games. so when im on google for example it moves to the left upper corner and does nothing else

specs:
3050 8gb single fan
intel i5-10400f
16gb of ram (plus some with page file)
2560x1440 screen

**Comment by michiel1106** [comment]
its not only valorant, to make sure it does work, what are the games it works on

**Comment by michiel1106** [comment]
and in fortnite it just jitter around thbe place

**Comment by ZCban** [comment]
This script work in 1920*1280 resolution u Need change It insidie script whit your resolution for valorant block any mouse emulation u Need a emulation hardware for bypass

**Comment by Qfc9** [comment]
Valorant is one of the few games which block win32api mouse movement calls. The way around this is by using a driver. Games with a 3rd person view will require you to adjust the `aaRightShift` so it doesn't register your player as the target.

**Comment by icedbug** [comment]
> its not only valorant, to make sure it does work, what are the games it works on



> and in fortnite it just jitter around thbe place

My mosuse flies everywehee. How did you manage to fix this?

**Comment by Foxy6670** [comment]
Using specifically CPU mode on my Ryzen 7 with integrated graphics, the mouse ONLY moves up-left when a human is detected, regardless of what it's detected on. Human detected on the bottom-right? Moves up-left. Human detected dead-center? Moves up-left. I can't figure out why this is happening, but to make it even more confusing, this does not happen in onnx-GPU mode.
