### ISSUE TITLE
AI cannot detect enemies therefore I cannot use the AI Aimbot

### ISSUE THREAD

**Issue by Badburnzzz** [RootKit-Org/AI-Aimbot#39]
Hello, thank you for the great contribution!

I am here to ask about my issue about it. I have successfully ran the code but unfortunately, when checking my live feed, It doesn't detect any enemies (APEX LEGENDS)

I hope that anyone can help me out. Thank you!

**Comment by ZCban** [comment]
U can try down value confidence, but i think u Need custom dataset for Better detection
