### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by MelvinSGjr** [RootKit-Org/AI-Aimbot#40]
AMD Ryzen.
In CMD:

C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1>py main.py
Downloading: "https://github.com/ultralytics/yolov5/archive/master.zip" to C:\Users\MelvinSGjr/.cache\torch\hub\master.zip
YOLOv5  2022-9-26 Python-3.10.7 torch-1.11.0+cu113 CPU

Fusing layers...
YOLOv5s summary: 213 layers, 7225885 parameters, 0 gradients
Adding AutoShape...
Traceback (most recent call last):
  File "C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1\main.py", line 211, in <module>
    main()
  File "C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1\main.py", line 105, in main
    im = torch.from_numpy(npImg).to('cuda')
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\cuda\__init__.py", line 216, in _lazy_init
    torch._C._cuda_init()
RuntimeError: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx

C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1>pip install --index-url https://test.pypi.org/simple/ --extra-index-url https://pypi.org/simple dxcam
Looking in indexes: https://test.pypi.org/simple/, https://pypi.org/simple
Requirement already satisfied: dxcam in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (0.0.5)
Requirement already satisfied: numpy in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from dxcam) (1.23.3)
Requirement already satisfied: comtypes in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from dxcam) (1.1.14)
Requirement already satisfied: opencv-python in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from dxcam) (4.6.0.66)

C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1>pip install -r requirements.txt
Requirement already satisfied: PyAutoGUI in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 1)) (0.9.53)
Requirement already satisfied: PyDirectInput in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 2)) (1.0.4)
Requirement already satisfied: Pillow in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 3)) (9.2.0)
Requirement already satisfied: opencv-python in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 4)) (4.6.0.66)
Requirement already satisfied: mss in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 5)) (6.1.0)
Requirement already satisfied: numpy in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 6)) (1.23.3)
Requirement already satisfied: pandas in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 7)) (1.5.0)
Requirement already satisfied: pywin32 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 8)) (304)
Requirement already satisfied: pyyaml in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 9)) (6.0)
Requirement already satisfied: tqdm in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 10)) (4.64.1)
Requirement already satisfied: matplotlib in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 11)) (3.6.0)
Requirement already satisfied: seaborn in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 12)) (0.12.0)
Requirement already satisfied: requests in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from -r requirements.txt (line 13)) (2.28.1)
Requirement already satisfied: pymsgbox in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from PyAutoGUI->-r requirements.txt (line 1)) (1.0.9)
Requirement already satisfied: PyTweening>=1.0.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from PyAutoGUI->-r requirements.txt (line 1)) (1.0.4)
Requirement already satisfied: pyscreeze>=0.1.21 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from PyAutoGUI->-r requirements.txt (line 1)) (0.1.28)
Requirement already satisfied: pygetwindow>=0.0.5 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from PyAutoGUI->-r requirements.txt (line 1)) (0.0.9)
Requirement already satisfied: mouseinfo in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from PyAutoGUI->-r requirements.txt (line 1)) (0.1.3)
Requirement already satisfied: pytz>=2020.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r requirements.txt (line 7)) (2022.2.1)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from pandas->-r requirements.txt (line 7)) (2.8.2)
Requirement already satisfied: colorama in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from tqdm->-r requirements.txt (line 10)) (0.4.5)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (4.37.3)
Requirement already satisfied: cycler>=0.10 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (0.11.0)
Requirement already satisfied: packaging>=20.0 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (21.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (1.0.5)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (1.4.4)
Requirement already satisfied: pyparsing>=2.2.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from matplotlib->-r requirements.txt (line 11)) (3.0.9)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 13)) (2022.9.14)
Requirement already satisfied: charset-normalizer<3,>=2 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 13)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 13)) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from requests->-r requirements.txt (line 13)) (1.26.12)
Requirement already satisfied: pyrect in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from pygetwindow>=0.0.5->PyAutoGUI->-r requirements.txt (line 1)) (0.2.0)
Requirement already satisfied: six>=1.5 in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas->-r requirements.txt (line 7)) (1.16.0)
Requirement already satisfied: pyperclip in c:\users\melvinsgjr\appdata\local\programs\python\python310\lib\site-packages (from mouseinfo->PyAutoGUI->-r requirements.txt (line 1)) (1.8.2)

C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1>py main.py
Traceback (most recent call last):
  File "C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1\main.py", line 211, in <module>
    main()
  File "C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1\main.py", line 75, in main
    camera = dxcam.create(region=region)
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 46, in __init__
    self._validate_region(self.region)
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 233, in _validate_region
    raise ValueError(
ValueError: Invalid Region: Region should be in 1920x1080
Exception ignored in: <function DXCamera.__del__ at 0x000002B026D0E710>
Traceback (most recent call last):
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1>py main.py
Traceback (most recent call last):
  File "C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1\main.py", line 211, in <module>
    main()
  File "C:\Users\MelvinSGjr\Desktop\AI-Aimbot-2.2.1\main.py", line 75, in main
    camera = dxcam.create(region=region)
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 112, in create
    return __factory.create(
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\__init__.py", line 71, in create
    camera = DXCamera(
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 46, in __init__
    self._validate_region(self.region)
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 233, in _validate_region
    raise ValueError(
ValueError: Invalid Region: Region should be in 1920x1080
Exception ignored in: <function DXCamera.__del__ at 0x000002360E86E710>
Traceback (most recent call last):
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 243, in __del__
    self.release()
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 238, in release
    self.stop()
  File "C:\Users\MelvinSGjr\AppData\Local\Programs\Python\Python310\lib\site-packages\dxcam\dxcam.py", line 138, in stop
    if self.is_capturing:
AttributeError: 'DXCamera' object has no attribute 'is_capturing'

**Comment by Xehia** [comment]
If it still doesn't work provide more details so we can understand better😉

**Comment by ZCban** [comment]
I think u dont have installated on PC cuda driver for yolo

**Comment by ZCban** [comment]
# CUDA 10.0
pip install torch==1.2.0 torchvision==0.4.0

# CUDA 9.2
pip install torch==1.2.0+cu92 torchvision==0.4.0+cu92 -f https://download.pytorch.org/whl/torch_stable.html

# CPU only
pip install torch==1.2.0+cpu torchvision==0.4.0+cpu -f https://download.pytorch.org/whl/torch_stable.html

**Comment by iceeburr** [comment]
Has anyone found a solution? If you did reply here or contact me on Discord - iceeburr#0746. Thanks!

**Comment by iceeburr** [comment]
I found a solution! Anyone that has this problem as well, you will need to make sure Python is in power saving mode. On windows 10/11 it's really simple. You go to your settings and search for "Graphics", then go to the graphics settings. You now should see a big list of programs there, click on "Browse" in the "Add App" section on the top, now navigate to this path in the file explorer and select python.exe `C:\Users\User\AppData\Local\Programs\Python]Python310`. Remember that your second python folder might be different depending on the python version, for some people it may be named Python309, etc. After you added python.exe, now select power saving mode (internal graphics card) in the options. This should fix the problem. Also you should restart your PC after this change, but I doubt it will do anything. (In my case I did have to restart it). Good luck. Btw I got some other errors like no module named pil or cannot import name "is_notebook", if you need help with that as well just DM me on Discord. iceeburr#0746.

**Comment by Qfc9** [comment]
Can this be closed then?

**Comment by ZCban** [comment]
@Qfc9 ValueError: Invalid Region: Region should be in 1920x1080 
dxcam as mss cannot record background applications.
check that you have entered the correct name of the program and before running the script that that program is in the foreground windowed or borderless mode.
the error in ython is always the first call the others depend on the first, in this case ValueError: Invalid Region: Region should be in 1920x1080
