### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by wolk3e** [RootKit-Org/AI-Aimbot#42]
ImportError: cannot import name 'is_notebook' from 'utils.general'
Had this issue when I tried to run main.py in powershell
Can you guys help me to fix this?

**Comment by ZCban** [comment]
U saved directory in a different way,try to save rootkit in desktop

**Comment by Kurisu-Preston** [comment]
It still ImportError when I save it in desktop.

**Comment by ZCban** [comment]
add to discord i can try help you ZC_winchesterbig#2814

**Comment by rogedkone** [comment]
Cant find Discord. Have same issue

**Comment by ZCban** [comment]
try reinstall requirements.txt the comand is: pip install -r requirements.txt --user

**Comment by rogedkone** [comment]
> try reinstall requirements.txt the comand is: pip install -r requirements.txt --user

redownload master and it works

**Comment by Qfc9** [comment]
The new update should fix this issue
