### ISSUE TITLE
Issue with videogamewindowtitle

### ISSUE THREAD

**Issue by cooldude315** [RootKit-Org/AI-Aimbot#45]
https://cdn.discordapp.com/attachments/925204205453602816/1042930031757885520/image.png i changed the name but still i does this

**Comment by ZCban** [comment]
U Need open program when start py

**Comment by iceeburr** [comment]
Has anyone found a solution? If you did reply here or contact me on Discord - iceeburr#0746. Thanks!

**Comment by ZCban** [comment]
The name of Windows program not correct check name using task manager. Launch game wait menu screen later launch rootkit

**Comment by Qfc9** [comment]
@ZCban Thanks for giving the answer
