### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ZCban** [RootKit-Org/AI-Aimbot#46]
Can someone more practical than me implement this in code it would help to keep a larger detection window by choosing only targets that pass around the value of a

import pyautogui
import time

pos = pyautogui.position()#pos mouse now
centro=(960,540)#center screen resolution 
a=100,100 #distance activation

distanzax= -(centro[0]-pos[0]) if pos[0] < centro[0] else pos[0]-centro[0]
distanzay= -(centro[1]-pos[1]) if pos[1] < centro[1] else pos[1]-centro[1]
print (distanzax,distanzay)

x= distanzax if 0<distanzax else distanzax-distanzax-distanzax
print(x)
y= distanzay if 0<distanzay else distanzay-distanzay-distanzay
print(y)
logic=(x,y)
print (logic)
if logic<a:
    pyautogui.moveTo (960,540)#change to target

**Comment by iceeburr** [comment]
You should have just tried to make it yourself and then make a pull request to get it added into the project. This is more of a suggestion and not an issue. Only requesting features and not contributing at all is bad, you should learn yourself as well. I highly suggest just to try and experiment with the code until you get it.

**Comment by ZCban** [comment]
I have already implemented in the rootkit code, I posted that piece of code where my idea comes from in order to allow others to improve it as a script

**Comment by Qfc9** [comment]
@ZCban What's your discord name? Since you helped people out here with their issues we can give you Champion status.

**Comment by ZCban** [comment]
@Qfc9  bacbtoback#2814

**Comment by Qfc9** [comment]
Are you in our discord server? It isn't showing that you are.

**Comment by Qfc9** [comment]
Found you.
