### ISSUE TITLE
Do I need to have a graphics card to do the hacking?

### ISSUE THREAD

**Issue by km1273551** [RootKit-Org/AI-Aimbot#49]
can i do this without a graphics card ?

**Comment by km1273551** [comment]
> 
I have a Graphic inside HD 4600
I can run the game with a low setting but I can't run all Games

**Comment by Qfc9** [comment]
This is not hacking, and no you don't have to have a GPU. You can use just a CPU with the normal main.py or onnx version. But your performance will not be the best.
