### ISSUE TITLE
Make game overlay when a game blocks win32api calls

### ISSUE THREAD

**Issue by Qfc9** [RootKit-Org/AI-Aimbot#5]
Only tracking Valorant right now

**Comment by ka1se2** [comment]
can't work in valorant

**Comment by AnnSir233** [comment]
Try running this Python application with administrator privileges. This often happens, especially when the permission level of the game is higher than your python.

**Comment by pang-lee** [comment]
@Qfc9 @AnnSir233 What the reason that valorant cannot work in the code?
Is it cause by win32api or other reason?
I'm also want to try in valorant, is there any suggestion?

**Comment by ZCban** [comment]
U need change mouse movement whit bypass in valorant

**Comment by LeeeSe** [comment]
@ZCban try to use ghub_mouse.dll but no use
