### ISSUE TITLE
dxcam capture speed

### ISSUE THREAD

**Issue by Monday-Leo** [RootKit-Org/AI-Aimbot#56]
Hi! The dxcam capture speed is unstable, between 0-10ms.The results are as follows. Why? Is it a bug?

1.1258000000000656
7.967900000000139
2.7013000000000176
2.367800000000031
3.877499999999756
0.017199999999828464
5.908699999999989
1.8077000000000787
1.7446000000003181
6.1069999999996405
1.5810000000002766
0.030100000000032878
1.7834999999997159
1.8221000000000487
0.040300000000215164
7.366799999999785
2.05870000000008
3.1911999999998386

**Comment by Qfc9** [comment]
No, it's how it does it. DXCam is one of the fastest for the bot. We are aware of some other modules that may be faster/more stable, but have yet to test it. I don't remember the name of it, but I think it was by Microsoft. It was using Directx12
