### ISSUE TITLE
Not working for testing the video game

### ISSUE THREAD

**Issue by pang-lee** [RootKit-Org/AI-Aimbot#65]
Hi, I'm trying using this code for running on Apex Game for testing and educational purpose, but seem like it doesn't work on that game, what issue can be cause by this situation?

is that the Yolo model did not train on detect the person inside the Apex game?

**Comment by ayetristan** [comment]
I was able to get it to work on apex, except ADS doesnt seem to function to well

**Comment by TOPDraling7485** [comment]
You can get help here https://t.me/+7HU4ehH2un0wZTVl
