### ISSUE TITLE
Not working on AMD GPU

### ISSUE THREAD

**Issue by BiskottoScriptato** [RootKit-Org/AI-Aimbot#66]
I get this error when i run this command: 

python .\export.py --weights ./yolov5s.pt --include onnx --half --imgsz 320 320 --device 0

Invalid CUDA '--device 0' requested, use '--device cpu' or pass valid CUDA device(s)

**Comment by ayetristan** [comment]
It works on amd gpu, im not sure why you would need to run that

i got it to work on my gpu

**Comment by Qfc9** [comment]
Ya, you might now need to remake the onnx model. 
Change the end from `--device 0` to `--device cpu`

It's gonna take a long time for it to export. It will look like it's frozen. It took 10-20 mins on a 3080.
