### ISSUE TITLE
No module named torch. 

### ISSUE THREAD

**Issue by Spunker7** [RootKit-Org/AI-Aimbot#67]
C:\AI\AI-Aimbot-main>python main.py
Traceback (most recent call last):
  File "C:\AI\AI-Aimbot-main\main.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'

For context, I am not very good at troubleshooting computer problems, and I apologize if this is a stupid question. I have tried a lot of different fixes on youtube and stackoverflow, and none of them seem to work. What do I do?

**Comment by phifogg** [comment]
Same issue here.
