### ISSUE TITLE
Mouse moves to top left corner on CPU mode

### ISSUE THREAD

**Issue by Foxy6670** [RootKit-Org/AI-Aimbot#81]
For whatever reason, only the onnx CPU mode has been causing a problem that moves the cursor to the top-left corner of the screen when a humanoid is detected. I added a print statement where it tells the win32api to move the cursor, and it constantly prints "-254 -255 0 0" when trying to move the cursor. The onnx AMD version works fine, though, which is interesting...
Any help is greatly appreciated!

**Comment by Qfc9** [comment]
Just use AMD version right now. I'll look into the CPU issue... One day. We also accept PRs
