### ISSUE TITLE
Need help with cps issue

### ISSUE THREAD

**Issue by discordmod400pounds** [RootKit-Org/AI-Aimbot#83]
the aimbot works fine but it stops working randomly it shuts off by its self how do i fix this?

![image](https://user-images.githubusercontent.com/126921632/230199204-7876d4bf-b1ac-47f7-bafc-f70a46531c80.png)

**Comment by discordmod400pounds** [comment]
![image](https://user-images.githubusercontent.com/126921632/230199253-b1ddad55-8bf9-4bd0-b707-d31976fbaeb4.png)

**Comment by icedbug** [comment]
Yeah I also wondering about that. But I think I hited a key or somting maybe Q

**Comment by Qfc9** [comment]
You hit the auto close key Q
