### ISSUE TITLE
Mouse not moving

### ISSUE THREAD

**Issue by alpgithubx** [RootKit-Org/AI-Aimbot#84]
I can see the AI is detecting people from the live feed, but the AI is not moving the mouse. What is the issue? There is no error message on the terminal. Can someone help? The libraries required are installed.

**Comment by alpgithubx** [comment]
> I can see the AI is detecting people from the live feed, but the AI is not moving the mouse. What is the issue? There is no error message on the terminal. Can someone help? The libraries required are installed.

I think they are installed...

**Comment by Qfc9** [comment]
Follow instructions to activate it
