### ISSUE TITLE
Ways to anti-ban

### ISSUE THREAD

**Issue by ueeseer** [RootKit-Org/AI-Aimbot#85]
Used and got banned in apex (Using EAC) in two days. Some anti-cheat already detects the algorithm so I suggest that maybe a wind_mouse algorithm could help situation?

**Comment by cannap** [comment]
maybe dont cheat xD

**Comment by spikeroog** [comment]
looks like a manual ban

**Comment by Qfc9** [comment]
You can be user reported and banned. EAC can not currently detect it.

**Comment by Qfc9** [comment]
Base project is made to be modified. So if you think you have a better approach, mod it and explore that approach!

**Comment by voxupe** [comment]
Add PID control to you movement logic
