### ISSUE TITLE
Trigger an EAC behavior ban.

### ISSUE THREAD

**Issue by iiiiilol** [RootKit-Org/AI-Aimbot#88]
- In Apex Legends, This aimbot triggers an almost instantous behavior ban. 
- Streaming from another devices and running program in other GPU still trigger a ban. 

I haven't try to rewrite mouse moving algorithm so I sus that might help?

**Comment by skullcheat** [comment]
sure you got instant ban in fire range take 10 min =)

**Comment by ZCban** [comment]
you used this project with the normal libraries to emulate the mouse you had to change the libraries with others bypass it is not the program but the movement of the mouse to be detected is banned
