### ISSUE TITLE
Aimbot tracks enemy unusally

### ISSUE THREAD

**Issue by grappleapples** [RootKit-Org/AI-Aimbot#89]
When aiambot is activated (running on main_onnx_nvidia.py to fortnite), it works however it doesn't track well. When tracking a player, it goes up and down as well as left and right in a weird motion making it hard to hit players with. 

Record of tracking a moving npc without mouse movement and the AI - Aimbot working funny:
(headshotmode = False)
https://streamable.com/zjllts

Not sure if these is because of the trained weights .pt file or because of another reason.

Thanks,
gp

**Comment by Iauygbagi** [comment]
Try decreasing mouseamp, but I still get this tracking problem when the enemy is fast running or jumping around

**Comment by Iauygbagi** [comment]
Also check on visuals if your character is interfering with the aim
